# Generated by Django 2.0.9 on 2019-12-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181203_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('남성', '남성'), ('여성', '여성'), ('female', 'Female'), ('not specified', 'Not specified')], max_length=80, null=True),
        ),
    ]
